version: "3.9"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      
  app-db:
    build: ./db-service
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  pokemon-service:
    build: ./pokemon-service
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./pokemon-service:/usr/src/app
      - ./db-models/models:/usr/src/models
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_db_dev
      - TEAM_SERVICE_URL=http://team-service:8000/teams/
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
      - PYTHONPATH=/usr/src
    depends_on:
      - app-db

  team-service:
    build: ./team-service
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./team-service:/usr/src/app
      - ./db-models/models:/usr/src/models
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_db_dev
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
      - PYTHONPATH=/usr/src
    depends_on:
      - app-db
     
  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - team-service
      - pokemon-service
